---

#D Simpson 2021, ds-04

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- block:

  - name: Copy dell-omsa.service file for systemd
    copy:
      src: dell-omsa.service
      dest: /etc/systemd/system/dell-omsa.service
      owner: root
      group: root
      mode: 0755

  - name: Enable and start dell-omsa.service
    service:
      name: dell-omsa
      state: started
      enabled: 'yes'

  become: "True"
...
